# Generated by Django 5.1.4 on 2025-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='bed.jpg', upload_to='category_images/'),
        ),
    ]
