# Generated by Django 5.1.6 on 2025-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_rating_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
