# Generated by Django 5.1.6 on 2025-03-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_advertisement_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
