# Generated by Django 5.1.6 on 2025-03-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
