# Generated by Django 5.1.6 on 2025-03-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_advertisement_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
