# Generated by Django 5.1.6 on 2025-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_card_expiry_order_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Request'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('exchange_requested', 'Exchange Requested'), ('exchanged', 'Exchanged'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], default='no_request', max_length=25),
        ),
    ]
