# Generated by Django 5.1.6 on 2025-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_order_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Request'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('exchange_requested', 'Exchange Requested'), ('exchanged', 'Exchanged'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], default='none', max_length=25),
        ),
    ]
