# Generated by Django 5.1.6 on 2025-03-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='new_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanged_order', to='store.order'),
        ),
    ]
