# Generated by Django 5.1.6 on 2025-03-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_exchange_new_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='new_order',
        ),
        migrations.AddField(
            model_name='exchange',
            name='tracking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
